name: translation_engine
description: "Translate library for flutter."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  path: ^1.8.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.1
  mockito: ^5.4.0
flutter:

