name: fluent_translate
description: "Offline translation engine for Flutter with layered processing, dictionary/phrase management, and JSON-file based storage."
version: 0.0.12
homepage: https://github.com/VernaculusF/translation_engine
repository: https://github.com/VernaculusF/translation_engine

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.0
  test: ^1.24.6
flutter:

